### ISSUE TITLE
syntax error, unexpected (when enabling app.)

### ISSUE THREAD

**Issue by jasonkuehl** [fcturner/passwords#144]
{"reqId":"NLA6RNVGYlRPPbDO3kFl","remoteAddr":"10.66.1.104","app":"PHP","message":"syntax error, unexpected '=>' (T_DOUBLE_ARROW) at \/var\/www\/owncloud\/apps\/passwords\/appinfo\/app.php#17","level":3,"time":"2016-03-17T16:10:56+00:00","method":"GET","url":"\/owncloud\/"}

When this error happens Owncloud will not display anything, only a white page.

Version
ownCloud 8.2.2 (stable)

**Comment by fcturner** [comment]
Fixed! Thanks for catching that. I was still testing in master.

**Comment by jasonkuehl** [comment]
Hey this did fix the site! Its does load now! However, I still get an error after I pulled the new code.

{"reqId":"S\/UtYBstoWMCFP7QiNjH","remoteAddr":"10.66.1.104","app":"PHP","message":"Class 'OCA\\Passwords\\Controller\\OC_Util' not found at \/var\/www\/owncloud\/apps\/passwords\/controller\/pagecontroller.php#20","level":3,"time":"2016-03-18T00:31:49+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/passwords\/"}

I did confirm the list does excite 
/var/www/owncloud/apps/passwords/controller

www-data www-data  962 Mar 18 00:24 pagecontroller.php

Do you want me to open a new ticket?

**Comment by fcturner** [comment]
No, I'll fix it right away.

**Comment by fcturner** [comment]
Fixed! I added one `\`, that should do the trick :smile:

**Comment by jasonkuehl** [comment]
![selection_269](https://cloud.githubusercontent.com/assets/9578513/13900420/0d19c148-eddc-11e5-9d07-a43273f4ecf1.png)
 Fixed! 

Ill let you know if I see any other issues. 

Great work Btw!

**Comment by fcturner** [comment]
Thanks! :+1:
