### ISSUE TITLE
Deleted passwords are shown with active ones

### ISSUE THREAD

**Issue by abishai** [fcturner/passwords#221]
Maybe it's PostgreSQL related, but I doubt.
I created a random password.
json -> deleted:false
If I delete it, the password goes to bin, however after page refresh with F5 button,  it's on the same page with active passwords.
json -> deleted:true

I looked into a database, deleted flag is turned on.

**Comment by fcturner** [comment]
Firefox?

**Comment by abishai** [comment]
Firefox 45.2.0 ESR

**Comment by fcturner** [comment]
I had a far more positive view of Firefox before I began developing web apps :smile:

**Comment by abishai** [comment]
and of pgsql? :)

**Comment by fcturner** [comment]
*[kept his mouth shut and waited patiently for another topic to respond]*
:sweat: :smile:

**Comment by fcturner** [comment]
Please download the latest master ([:package:zip](../archive/master.zip) or [:package:tarball](../archive/master.tar.gz)) and report back if this still persists with latest Firefox. Thanks!

**Comment by abishai** [comment]
I'm tracking ESR branch of Firefox, so now it's 45.3.0 version. I still have the issue. I installed tarball and truncated oc_passwords table.

Now I have 404 on PUT request. JSON response is "No matching entry found". 
BTW, plain password is sent in input json.

**Comment by abishai** [comment]
id property is not populated correctly. That UNION query for password population has internal flaw, I suppose in CAST method.

**Comment by abishai** [comment]
It has flaw indeed. You casting id to CHAR.
In postgresql this means you casting it to CHAR(1), so effectively truncating value for ids > 9
Correct CAST is to VARCHAR.

**Comment by abishai** [comment]
OK, I fixed it locally. Now PUT works. Original issue still here.
owncloud=# select id, deleted from oc_passwords;
 id | deleted 
----+---------
 24 | t
(1 row)

I still see it as active entry. In Chrome too.

**Comment by fcturner** [comment]
> BTW, plain password is sent in input json.

How do you mean? If you're using PUT, you already authenticated. Plain passwords are only available after authentication, as they need to be decrypted. That only happens with a valid username and password. 

> It has flaw indeed. You casting id to CHAR.

So if I change this to VARCHAR, we're good to go?

**Comment by abishai** [comment]
1. But is it necessary to send plain passwords to server after authentication? For example, Keepass container in owncloud share will be secure even if owncloud installation compromised. Plain passwords can be read if attacker has access to owncloud sources.
2. Yep, if other backends support this. However, we still have original issue.

**Comment by fcturner** [comment]
No, I guess you don't understand how this works. My app is just as safe as KeePass, or maybe even safer. Passwords won't be 'served' after authentication. They are decrypted server side (so the API works) after successful login in the ownCloud instance where the password was created in (so that adds client side encryption, as credentials are needed for the API too). So you don't only need to hack the ownCloud instance, you need valid ownCloud credentials of every specific user too and thus full access to the database server. And the same password salt in the local config file. Administrators cannot decrypt the passwords of users, because it requires the ownCloud password of that users, which is stored only encrypted by ownCloud itself. 

Even if the credentials are known, users can set a master password to restrict access to their passwords. Without that master password, passwords cannot be decrypted. 

The KeePass container app is nothing more than a fork (edited free copy) of this app. It just validates the KeePass credentials and shows all passwords. I think, especially after my last updates, ownCloud Passwords is far more robust. 

So, hacking my app to retrieve actual passwords requires a lot more than just ownCloud being compromised.

**Comment by abishai** [comment]
I see.

However I disagree about KeePass - I bear in mind KeePass standalone (desktop) app, in this scheme ownloud is just webdav medium transferring encrypted container. So, technically password container is totally separated from owncloud instance - even compromisation of server root gives nothing to possible attacker as encryption key + password needed to decrypt container and decryption done after container copied to my machine.

I'm not saying that your app is not secure, I just try to figure the risks :)

OK, back to our issue - I have the same problem with deleted passwords in Google Chrome under Windows. I'd try to see if I can find obvious reason of this. Maybe, it's another postgresql trick.

**Comment by fcturner** [comment]
Questions:
Do you have the KeePass file on your ownCloud?
Do you open the file in the KeePass app?
Do you get access to your KeePass passwords when you've given in your KeePass credentials? 

Then that's less safe than using my app. You basically save everything to a file. Saving to a database is far more secure and allows sharing with other ownCloud users. 

I understand that you believe in the security of my app. And you should, it's solid as a rock :wink:
KeePass isn't really that good if you can have it stored encrypted really well in a database. 

Right, indeed back to the issue. Giving that this issue exists on Windows with Chrome too, this must be database (PGSQL) related. I'll try to fix it.

**Comment by abishai** [comment]
js booleans don't have numeric representation. I suspect other databases return 0 or 1, pgsql returns true/false, so row.deleted is boolean in our case. Possible solution: explicitly cast deleted value to boolean when running query against database and fix comparison. 
```
                        if (row.deleted == 1) {
                                if (is_sharedby) {
                                        var html_row = '<tr class="is_deleted is_sharedby" sharedby="' + row.user_id + '" ';
                                } else {
                                        var html_row = '<tr class="is_deleted" ';
                                }
```

**Comment by fcturner** [comment]
This could indeed help. I'll try that and report back.

**Comment by fcturner** [comment]
According to https://www.postgresql.org/docs/9.1/static/datatype-boolean.html you are wrong:

![image](https://cloud.githubusercontent.com/assets/7526559/18708835/1e931c40-7ffd-11e6-9fd0-7db501579f00.png)

But Javascript *can* check for numbers, even when values are true/false:
```js
var value = true;
alert(value); // true
alert(~value); // 1

var value = false;
alert(value); // false
alert(~value); // 0
```

**Comment by fcturner** [comment]
Please download the latest master ([:package:zip](../archive/master.zip) or [:package:tarball](../archive/master.tar.gz)).

**Comment by abishai** [comment]
I used typeof(row.deleted) on my system and found that variable is .... string. That's why comparison is not working. I think it's better to cast it to boolean on php side.

**Comment by fcturner** [comment]
Please download the latest master ([:package:zip](../archive/master.zip) or [:package:tarball](../archive/master.tar.gz)). It should be fixed now.

**Comment by fcturner** [comment]
@abishai Can this be closed? Can I help you with anything else?

**Comment by abishai** [comment]
@fcturner problem is not fixed. I still can observe deleted passwords among active. 
Maybe I described problem slightly wrong - the problem with comparison is that deleted value is (string)true.

However, I seriously suggest to cast value to boolean in password.php adding (bool) to deleted flag. From my point of view, even if issue will be fixed in js code this would be wrong - data model shouldn't depend on database engine.

**Comment by fcturner** [comment]
I agree. Could you please do a pull request?

**Comment by abishai** [comment]
Done. I believe I did it right.

**Comment by fcturner** [comment]
Thanks! I'll test it right away and implement it.

**Comment by fcturner** [comment]
👍 Thanks!
