### ISSUE TITLE
Import of KeePass CSV (1.x) fails

### ISSUE THREAD

**Issue by fcturner** [fcturner/passwords#57]
*By corwyn @ [apps.owncloud.com](https://apps.owncloud.com/content/show.php?content=170480)*

-------

Passwords 8.0.11
OwnCloud 8.1.1-12 (current stable)

When I try to import my passwords CSV created with KeePass CSV (1.x), it reports This is not a valid CSV file. I also tried to import as Other CSV, same results.

I double checked the format in a text editor, it appears to be correct, I checked it in Excel, also reads no problem. The file is a valid CSV.

Data format (header line):

"Account","Login Name","Password","Web Site","Comments"

**Comment by fcturner** [comment]
I found that a CSV ending with an empty line throws the error.

**Comment by fcturner** [comment]
Fixed as of 8.0.12.

**Comment by fcturner** [comment]
Still doesn't work :cry: 
Now considered a valid CSV, but import is broken.

This should be possible:
```csv
"Account","Login Name","Password","Web Site","Comments"
"Apple ID","appleuser","testpw","apple.com","This is a test note"

```
Need to fix:
- [ ] Account, Login Name and Password aren't saved to database
- [ ] Passwords counts as two passwords due to empty line; should be `total = 2` and `header = 1`, so `count = 1`
- [ ] URL doesn't work, since http:// needs to be added

**Comment by Yamakasi** [comment]
Any news on this ? I think everyone wants to import :)

Great work tho!

**Comment by fcturner** [comment]
Yes, almost done! 

I already solved this, but there's still a small bug concerning passwords and usernames containing a `<` or `>`. When I've fixed that, I will release it as 8.0.13.

**Comment by fcturner** [comment]
Now really fixed as of 8.0.13.

**Comment by muyiscoi** [comment]
Yay! I can indeed confirm that importing now works. However, I noticed that some of the passwords were not imported correctly, especially the ones with special characters like " and \.
For instance, I have a password "93}sjgc\070zk2B" (without the quotes at the ends) and it was imported as "93}sjgc\\070zk2B" and another originally ""_b0G"A2[-[]4Ky" (again, without the quotes at the ends) was imported as "\"_b0G\"A2[-[]4Ky". 
Best I can figure, it seems like the Backslash is inserted in the same way its used in UNIX command line, i.e to escape special characters, however, in this case, its being added to the password when imported. I'm probably wrong in this assessment though, as I'm not a programmer.

**Comment by fcturner** [comment]
Wow, great explained! I wish everyone included examples :smile:

Concerning your problem, I don't think this can be fixed. The problem is, the output CSV from KeePass (or every other source, even ownCloud Passwords) contains lines split by commas and every value is preceded and succeeded by a ". This is done to be able to import values containing a comma, or else the lines with such a value would split there (since it is a *comma* separated values file). So when a password contains a ", your source will always escape that character by preceding it with a backslash. When importing such values, one can never tell if the backslash was added to the password for escaping another character or if it belongs there. 
OR... Source values with a backslash are escaped with a double backslash. I need to check this. Last hope I've got :)

**Comment by muyiscoi** [comment]
I see. That makes sense. Its not a huge issue for me. The two instances above are the only times I had that issue as I mostly don't generate passwords with special characters. I'll just manually edit them and I should be fine. 
Thanks for all your work!.

**Comment by Yamakasi** [comment]
This issue is still here for me on .13

**Comment by fcturner** [comment]
@Yamakasi Would you please post your CSV content here, after replacing the website, usernames and URLs with " "?

**Comment by Yamakasi** [comment]
That is a little but difficult as it's a very huge one. Where could it fail on ?

**Comment by fcturner** [comment]
Well, in 8.0.13 I implemented *a lot* of error descriptions, so what does it say when you import??

**Comment by Yamakasi** [comment]
Invalid CSV, I use lots of characters on some passwords ['\/` etc... is there still a problem with those ?

**Comment by fcturner** [comment]
No, it shouldn't. But the newest version tells you **why** it is invalid. So what is the second line of the message?

**Comment by Yamakasi** [comment]
There is no second line, and I emptied my cache so be sure I have the right .js

**Comment by fcturner** [comment]
I'm very sorry to say, but that's impossible. I just checked again and there's no more error with just the text 'This is an invalid CSV file'. 

So maybe your browser throws a JavaScript error. Please don't say you are using a made-by-Microsoft browser :smile:

**Comment by Yamakasi** [comment]
Ok, some files were not overwritten and I got a new update message after removing the passwords folder and unpack and mv it again.

Now I get that one or multiple inputs/values are unquoted.

**Comment by fcturner** [comment]
So that's it then :)

The lines in your file do not start with a " meaning that your values aren't quoted as "value1", "value2", ... which makes your file incompatible. 
What software are you using?

**Comment by Yamakasi** [comment]
Keepass V2 and I export as V1

**Comment by fcturner** [comment]
All is quoted?? That's strange. Are there any lines in your CSV that do not start with a quotation mark, except for empty lines?
I wonder if KeePass does additions to its output like comments or something. Or division in groups.

All can be fixed :smile: 
Just need to know where it goes wrong.

**Comment by Yamakasi** [comment]
No, all are like:

"Account","Login Name","Password","Web Site","Comments"

Are you sure that things like "*.csdcdscds.tld", etc doesn't matter ?

I get the feeling that something still goes wrong with escaping.

Yap all can be fixed ;) thanks so far!

**Comment by fcturner** [comment]
No, shouldn't matter. The algorithm is like this (example line):
`"Testaccount","Testloginname","*.csdcdscds.tld","TestURL","Testnotes"`

1. Strip first and last quotation mark:
`Testaccount","Testloginname","*.csdcdscds.tld","TestURL","Testnotes`

2. Split line into array with `","` as delimiter
`array[0] = Testaccount`
`array[1] = Testloginname`
`array[2] = *.csdcdscds.tld`
`array[3] = TestURL`
`array[4] = Testnotes`
3. Import values in table

So an asterisk or dot should import perfectly. Besides, the quotation error can only be thrown [at these three lines](https://github.com/fcturner/passwords/blob/8.0.13/js/script.js#L1487-L1489):
```javascript
1487 if (lines[i].substr(0, 1) != '"') {
1488 	InvalidCSV(t('passwords', 'This file contains one or more values without quotation marks.'));
1489 }
```
This means it just checks on the very first character of every line (ignoring empty lines). If you get this error, there must be at least one line which does not start with `"` and is not empty... Can you please check this?

**Comment by fcturner** [comment]
By the way, you're helping a lot of people by helping me fix this! :+1:

**Comment by Yamakasi** [comment]
OK, I just checked and even removed the last empty line which most of the time can cause an issue.

I'm investigating what can be wrong with the file by splitting it up and importing it.

**Comment by Yamakasi** [comment]
OK, checked out, does't matter at all, it's not even accepted with one single line in it.

**Comment by fcturner** [comment]
Great! Since 8.0.12 empty lines are ignored anyway, but I like your approach of importing the file part by part. Curious to hear your verdict.

**Comment by fcturner** [comment]
No, you should split it at every 10 of 100 lines or so. If you select KeePass, your file contains a header. So a KeePass file with only one line does not contain any password and throws an error (which it should).

**Comment by fcturner** [comment]
Just import with 'Other CSV' and turn off file headers.

**Comment by Yamakasi** [comment]
Hi I did that with less lines, and one passwordline left... the same for "Other CSV", same message.

**Comment by fcturner** [comment]
Well, as the codes states, if you get the error `This file contains one or more values without quotation marks.`, there must be at least one non-empty line which does not start with `"`. I don't know how I can reproduce this.

**Comment by Yamakasi** [comment]
But it also happens when I add one line to the file with a password and all filled and quoted.

Can you give a working examplem one line from your side that works ?

**Comment by IzK666** [comment]
Hi!
I've tried to import a sample KeePass file and works fine.
Only fails with those characters: \ and ", which are escaped as \\ and \".

I've used Keepass 2.30.

PS:
passwordCSV = passwordCSV.replace(/\\\"/g,'"');
passwordCSV = passwordCSV.replace(/\\\\/g,'\\');
and should be done with notes too (and login?).

**Comment by Yamakasi** [comment]
I think needs to be done for all ?

**Comment by fcturner** [comment]
Yes, see issue #76.

@Yamakasi Can this be closed? Seems to work for me, for @IzK666 and for @muyiscoi...

**Comment by Yamakasi** [comment]
Yep can be closed as of #76
